
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team02-s24-4pm-8
owner: ucsb-cs156-s24
repo_name: team02-s24-4pm-8
pull_requests: [{"author":{"id":"U_kgDOBdHsdg","is_bot":false,"login":"charlene-patenaude","name":""},"headRefName":"cp-UCSBOrganization-create-db","number":44,"title":"Add database table for UCSBOrganization","url":"https://github.com/ucsb-cs156-s24/team02-s24-4pm-8/pull/44"},{"author":{"id":"U_kgDOBdHiHw","is_bot":false,"login":"emilythai","name":""},"headRefName":"et-RecommendationRequest-create-db","number":43,"title":"Add database table for RecommendationRequest","url":"https://github.com/ucsb-cs156-s24/team02-s24-4pm-8/pull/43"}]
