
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team02-s24-4pm-8
owner: ucsb-cs156-s24
repo_name: team02-s24-4pm-8
pull_requests: [{"author":{"id":"MDQ6VXNlcjYxMzA2Mzkw","is_bot":false,"login":"Jumshim","name":"jeffmun"},"headRefName":"Jeffrey-HelpRequestControllerEndpoints","number":57,"title":"jm - added GET single, PUT, DELETE endpoints and tests for Help Request controller","url":"https://github.com/ucsb-cs156-s24/team02-s24-4pm-8/pull/57"},{"author":{"id":"U_kgDOBXv2pw","is_bot":false,"login":"rainakakani21","name":""},"headRefName":"rk-UCSBDiningCommonMenuItem-create-db","number":56,"title":"added database stuff for ucsbdiningcommonmenuitem","url":"https://github.com/ucsb-cs156-s24/team02-s24-4pm-8/pull/56"},{"author":{"id":"U_kgDOBdHhMA","is_bot":false,"login":"niyati-m","name":""},"headRefName":"Niyati-Articles-Controller","number":51,"title":"Niyati-Articles-Controller and Tests","url":"https://github.com/ucsb-cs156-s24/team02-s24-4pm-8/pull/51"},{"author":{"id":"U_kgDOBdHhMA","is_bot":false,"login":"niyati-m","name":""},"headRefName":"Niyati-Articles-create-db","number":45,"title":"NIyati-Articles Finished Databases","url":"https://github.com/ucsb-cs156-s24/team02-s24-4pm-8/pull/45"}]
