
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team02-s24-4pm-8
owner: ucsb-cs156-s24
repo_name: team02-s24-4pm-8
pull_requests: [{"author":{"id":"U_kgDOBdHhMA","is_bot":false,"login":"niyati-m","name":""},"headRefName":"Niyati-Articles-Controller","number":51,"title":"Niyati-Articles-Controller and Tests","url":"https://github.com/ucsb-cs156-s24/team02-s24-4pm-8/pull/51"},{"author":{"id":"U_kgDOBdHiHw","is_bot":false,"login":"emilythai","name":""},"headRefName":"et-RecommendationRequest-addPUT","number":50,"title":"Add PUT on RecommendationRequest Controller ","url":"https://github.com/ucsb-cs156-s24/team02-s24-4pm-8/pull/50"},{"author":{"id":"U_kgDOBdHiHw","is_bot":false,"login":"emilythai","name":""},"headRefName":"et-RecommendationRequest-addDELETE","number":49,"title":"Add DELETE on RecommendationRequest Controller ","url":"https://github.com/ucsb-cs156-s24/team02-s24-4pm-8/pull/49"},{"author":{"id":"U_kgDOBdHiHw","is_bot":false,"login":"emilythai","name":""},"headRefName":"et-RecommendationRequest-addGET-single","number":48,"title":"Add GET a single request on RecommendationRequest Controller","url":"https://github.com/ucsb-cs156-s24/team02-s24-4pm-8/pull/48"},{"author":{"id":"MDQ6VXNlcjkxMjk0MDI1","is_bot":false,"login":"vaaniarora","name":"vaani arora"},"headRefName":"v-menuitem-create-db","number":47,"title":"Created database for Menu Item Reviews","url":"https://github.com/ucsb-cs156-s24/team02-s24-4pm-8/pull/47"},{"author":{"id":"U_kgDOBdHiHw","is_bot":false,"login":"emilythai","name":""},"headRefName":"et-RecommendationRequest-create-controller","number":46,"title":"Add Controller with GET for all and POST","url":"https://github.com/ucsb-cs156-s24/team02-s24-4pm-8/pull/46"},{"author":{"id":"U_kgDOBdHhMA","is_bot":false,"login":"niyati-m","name":""},"headRefName":"Niyati-Articles-create-db","number":45,"title":"NIyati-Articles Finished Databases","url":"https://github.com/ucsb-cs156-s24/team02-s24-4pm-8/pull/45"},{"author":{"id":"U_kgDOBdHsdg","is_bot":false,"login":"charlene-patenaude","name":""},"headRefName":"cp-UCSBOrganization-create-db","number":44,"title":"Add database table for UCSBOrganization","url":"https://github.com/ucsb-cs156-s24/team02-s24-4pm-8/pull/44"},{"author":{"id":"U_kgDOBdHiHw","is_bot":false,"login":"emilythai","name":""},"headRefName":"et-RecommendationRequest-create-db","number":43,"title":"Add database table for RecommendationRequest","url":"https://github.com/ucsb-cs156-s24/team02-s24-4pm-8/pull/43"}]
